on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_CRAN_INCOMING_: false
      _R_CHECK_CRAN_INCOMING_REMOTE_: false
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::packages/CohortUtilisation, local::packages/CohortCosts, local::packages/CohortEconomics, any::rcmdcheck
          needs: check

      - name: Check CohortUtilisation
        run: Rscript -e "rcmdcheck::rcmdcheck('packages/CohortUtilisation', args = c('--no-manual', '--as-cran'), error_on = 'warning')"

      - name: Check CohortCosts
        run: Rscript -e "rcmdcheck::rcmdcheck('packages/CohortCosts', args = c('--no-manual', '--as-cran'), error_on = 'warning')"

      - name: Check CohortEconomics
        run: Rscript -e "rcmdcheck::rcmdcheck('packages/CohortEconomics', args = c('--no-manual', '--as-cran'), error_on = 'warning')"

      - name: Check root omopHeor
        uses: r-lib/actions/check-r-package@v2
